// Undef debug macros defined in debug_macros.hpp

#undef CPPTOOLS_LOCAL_DEBUG_MACRO
#undef CPPTOOLS_DEBUG_ASSERT
#undef CPPTOOLS_DEBUG_POLICY
#undef CPPTOOLS_DEBUG_ENABLED
#undef CPPTOOLS_NOEXCEPT_RELEASE
#undef CPPTOOLS_NOEXCEPT_RELEASE_AND