// Undef debug macros defined in debug_macros.hpp

#undef @CONFIGURE_DEBUG_PROJECT_MACRO@_LOCAL_DEBUG_MACRO
#undef @CONFIGURE_DEBUG_PROJECT_MACRO@_DEBUG_ASSERT
#undef @CONFIGURE_DEBUG_PROJECT_MACRO@_DEBUG_POLICY
#undef @CONFIGURE_DEBUG_PROJECT_MACRO@_DEBUG_ENABLED
#undef @CONFIGURE_DEBUG_PROJECT_MACRO@_NOEXCEPT_RELEASE
#undef @CONFIGURE_DEBUG_PROJECT_MACRO@_NOEXCEPT_RELEASE_AND