#ifndef TOOLS__EXCEPTIONS__BAD_SYNTAX__ERROR
#define TOOLS__EXCEPTIONS__BAD_SYNTAX__ERROR

#include "../make_basic_exception.hpp"

DECLARE_BASIC_EXCEPTION(BadSyntaxError)

#endif//TOOLS__EXCEPTIONS__BAD_SYNTAX__ERROR