#ifndef TOOLS__EXCEPTIONS__FILE_NOT_FOUND_ERROR
#define TOOLS__EXCEPTIONS__FILE_NOT_FOUND_ERROR

#include "../make_basic_exception.hpp"

DECLARE_BASIC_EXCEPTION(FileNotFoundError)

#endif//TOOLS__EXCEPTIONS__FILE_NOT_FOUND_ERROR