#ifndef TOOLS__EXCEPTIONS__RANGE_BOUNDS_EXCEEDED_ERROR_HPP
#define TOOLS__EXCEPTIONS__RANGE_BOUNDS_EXCEEDED_ERROR_HPP

#include "../../tools/make_basic_exception.hpp"

DECLARE_BASIC_EXCEPTION(RangeBoundsExceededError)

#endif//TOOLS__EXCEPTIONS__RANGE_BOUNDS_EXCEEDED_ERROR_HPP