#ifndef TOOLS__EXCEPTIONS__UNMATCHED_ARRAY_SIZE_ERROR_HPP
#define TOOLS__EXCEPTIONS__UNMATCHED_ARRAY_SIZE_ERROR_HPP

#include "../../tools/make_basic_exception.hpp"

DECLARE_BASIC_EXCEPTION(UnmatchedArraySizeError)

#endif//TOOLS__EXCEPTIONS__UNMATCHED_ARRAY_SIZE_ERROR_HPP