#ifndef TOOLS__MICRO_SHELL__MICRO_SHELL_CODES_HPP
#define TOOLS__MICRO_SHELL__MICRO_SHELL_CODES_HPP

#define SHELL_EXIT -1
#define SHELL_COMMAND_SUCCESS 0
#define SHELL_COMMAND_FAILURE 1
#define SHELL_COMMAND_BAD_ARGUMENTS 2
#define SHELL_COMMAND_NOT_FOUND 3

#endif//TOOLS__MICRO_SHELL__MICRO_SHELL_CODES_HPP